### ISSUE TITLE
Support Backblaze B2 Cloud Storage

### ISSUE THREAD

**Issue by tarikd** [s3fs-fuse/s3fs-fuse#272]
Hi everyone,

Backblaze just announced B2 an S3 competitor 4 times cheaper. I would love that s3fs-fuse be compatible with this new cloud storage solution.

Cheers !

**Comment by andrewgaul** [comment]
B2 has a different API than S3:

https://www.backblaze.com/b2/docs/

It might be possible to add this to s3fs, but perhaps adding B2 support to S3Proxy would be more appropriate.

**Comment by pjz** [comment]
I opened a ticket for this on S3Proxy [here](https://github.com/andrewgaul/s3proxy/issues/98)

**Comment by DreamFlasher** [comment]
As https://github.com/gaul/s3proxy/issues/98 is closed and s3proxy supports b2 -- does that mean this ticket here can be closed because s3proxy is safely to be used with s3fs?

**Comment by gaul** [comment]
Can someone test this?  s3fs stores directory metadata in objects ending in `/` but B2 does not allow this:

https://www.backblaze.com/b2/docs/files.html#fileNames

**Comment by gaul** [comment]
Closing due to inactivity.

**Comment by dreamflasher** [comment]
So does this mean this doesn't work?

**Comment by gaul** [comment]
s3fs will never support Backblaze natively since its B2 protocol differs from S3.  It is possible that using s3fs with S3Proxy works but there are some B2 restrictions with objects ending with `/`.  If this does not work I recommend trying [b2_fuse](https://github.com/sondree/b2_fuse) instead.

**Comment by JordanMagnuson** [comment]
I also want to switch from using S3 to Backblaze B2 for my mounted file system. Can anyone confirm that that have found a dependable solution in either s3fs + s3proxy or b2_fuse?

**Comment by OJFord** [comment]
B2 now offers an [S3 compatible API](https://www.backblaze.com/b2/docs/s3_compatible_api.html) - i.e. `aws --endpoint-url=s3.region.backblazeb2.com s3[api] ...` should work.

So, for anyone else looking to see if s3fs supports not-real-S3 S3-like storage, yep:
https://github.com/s3fs-fuse/s3fs-fuse/wiki/Non-Amazon-S3

That should now work with the S3 endpoint of your B2 bucket.

**Comment by gaul** [comment]
Backblaze supports parts of the S3 API but their implementation of MPU copy part has some issues.  I reported this to their team but have not heard back yet.  I tested via:

```
$ S3_URL=https://s3.us-west-001.backblazeb2.com S3FS_CREDENTIALS_FILE=/path/to/.passwd make check -C test
$ cat test/test-suite.log
...
FAIL: test_mv_file
FAIL: test_list
FAIL: test_remove_nonempty_directory
FAIL: test_external_modification
FAIL: test_read_external_object
FAIL: test_multipart_copy
FAIL: test_multipart_mix
FAIL: test_extended_attributes
FAIL: test_content_type
FAIL: test_cache_file_stat
SUMMARY for ./integration-test-main.sh: 26 tests passed.  10 tests failed.
```

Note that some of these tests failed due to litter from previous test failures.

**Comment by gaul** [comment]
Most of these tests failed due to an issue in the test configuration.  However, `test_multipart_mix` still fails due to a Backblaze S3 incompatibility.  Adding the flag `-o nomixupload` works around this.  I also added a section for Backblaze here:

https://github.com/s3fs-fuse/s3fs-fuse/wiki/Non-Amazon-S3#backblaze

**Comment by JordanMagnuson** [comment]
Thanks for your work on this, gaul! What does the nomixupload flag actually do? At first I thought it was no mluti-part upload, but I see that that is a different flag.

**Comment by gaul** [comment]
With nomixupload, a small change to a file requires s3fs to upload (and possibly download) the entire object.  With the mixupload optimization, s3fs can use multipart copy to avoid uploading most of the bytes.  This is likely an oversight in the Backblaze implementation and I sent further debugging information to their team.

**Comment by malaysf** [comment]
Hello, I'm a developer at Backblaze. Thank you for testing s3fs with our S3 compatible API and for letting us know about this issue. I looked into the test failures and they are caused by a known limitation described under the "Successive Calls" section in the [S3 compatibility guide](https://www.backblaze.com/b2/docs/s3_compatible_api.html):

> When uploading multiple versions of the same file within the same second, the possibility exists that the processing of these versions may not be in order. Backblaze recommends delaying uploads of multiple versions of the same file by at least one second to avoid this situation.
> Similarly, when hiding a file within the same second as uploading that file, it is possible that the file may not actually be hidden. To avoid such a situation, please delay such calls on the same file by at least one second.

I forced a delay in the calls locally and the tests succeeded. This is on our roadmap to address but I don't have an estimate on when this work will be completed.

**Comment by gaul** [comment]
Thanks for your investigation!  Fixing #1013 would work around some but not all of these symptoms but this is a subtle change.  Can you respond here when Backblaze fixes the semantics of overwrites?

**Comment by malaysf** [comment]
Yes, I will post back here when this is fixed.
